import { PrismaClient } from '@prisma/client';
import { UniverseContentBlob } from '@/lib/prisma-content-blobs';

const prisma = new PrismaClient();

async function main() {
    // Create default universe using UniverseContentBlob structure
    const defaultUniverse: UniverseContentBlob = {
        id: '', // id will be generated by Prisma
        title: 'Zeta Gundam RPG',
        content: {
            description: 'Zeta Gundam RPG is a role-playing game based on the Zeta Gundam anime.',
            imageId: '', // You can set a default imageId or leave it empty
        }
    };

    await prisma.universes.create({
        data: defaultUniverse,
    });

  // Example: Create multiple posts
  await prisma.post.createMany({
    data: [
      { title: 'First Post', content: 'This is the first post content.', published: true },
      { title: 'Second Post', content: 'This is the second post content.', published: false },
    ],
  });

  console.log('Database seeded successfully!');
}

main()
  .catch((e) => {
    console.error(e);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });